name: Prod - Deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build-prod

      - name: "Prepare SSH key and known hosts"
        # https://github.com/symfony/cli/issues/227#issuecomment-601680974
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          rsync --verbose -rSlh --stats --delete dist/klaro/browser/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PROD_WEBPATH }}
